backend/routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

//Route::get('/', function () {
//    return view('welcome');
//});


Route::group(['prefix' => (app()->environment() == 'testing') ? 'en' : LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function() {
    AdvancedRoute::controller('auth', 'AuthController');
    Route::group(['middleware' => ['auth']], function() {
        AdvancedRoute::controller('profile', 'ProfileController');
        Route::group(['middleware' => ['IsAdmin'], 'prefix' => 'admin'], function() {
            AdvancedRoute::controller('translator', 'Admin\TranslatorController');
            AdvancedRoute::controller('countries', 'Admin\CountriesController');
            AdvancedRoute::controller('roles', 'Admin\RolesController');
            AdvancedRoute::controller('users', 'Admin\UsersController');
            AdvancedRoute::controller('configs', 'Admin\ConfigsController');
            AdvancedRoute::controller('posts', 'Admin\PostsController');
            AdvancedRoute::controller('slides', 'Admin\SlidesController');
            AdvancedRoute::controller('contacts', 'Admin\ContactsController');
            AdvancedRoute::controller('messages', 'Admin\MessagesController');
            AdvancedRoute::controller('pages', 'Admin\PagesController');
            AdvancedRoute::controller('search', 'Admin\SearchController');
            AdvancedRoute::controller('dashboard', 'Admin\DashBoardController');
            AdvancedRoute::controller('products', 'Admin\ProductsController');
            AdvancedRoute::controller('orders', 'Admin\OrdersController');
            AdvancedRoute::controller('sections', 'Admin\SectionsController');
            AdvancedRoute::controller('currencies', 'Admin\CurrenciesController');
            AdvancedRoute::controller('reviews', 'Admin\ReviewsController');
            AdvancedRoute::controller('vouchers', 'Admin\VouchersController');
        });
    });
    AdvancedRoute::controller('notifications', 'NotificationsController');
    AdvancedRoute::controller('posts', 'PostsController');
    AdvancedRoute::controller('products', 'ProductsController');
    AdvancedRoute::controller('pages', 'PagesController');
    Route::get('/contact', 'PagesController@contact');

    Route::get('/admin', function() {
        return redirect('auth/login');
    });

    AdvancedRoute::controller('/', 'HomeController');
    AdvancedRoute::controller('ajax', 'AjaxController');
});



//Route::prefix('api')->group(function () {
//    require_once __DIR__ . '/api.php';
//});

backend/app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends \App\Models\BaseModel {

    use SoftDeletes,
        \App\Models\Traits\CreatedBy,
        \App\Models\Traits\FinalPrice,
        \App\Models\Traits\Sluggable,
        \App\Models\Traits\HasAttach,
        \Laravel\Scout\Searchable,
        \Spatie\Translatable\HasTranslations;

    ///////////////////////////// has translation
    public $translatable = ['title', 'slug', 'summary', 'content', 'tags', 'meta_description', 'meta_keywords'];
    protected $table = "products";
    protected $guarded = [
        'deleted_at',
        'image',
    ];
    protected $hidden = [
        'deleted_at',
    ];
    static $attachFields = [
        'image' => [
            'sizes' => ['large' => 'resize,400x240', 'small' => 'crop,200x120']
        ],
    ];
    public $rules = [
        'category_id' => 'required',
        'title' => 'required',
        'summary' => 'required',
        'content' => 'required',
        'price' => 'required|numeric',
        'discount' => 'required|numeric',
        'image' => 'nullable|image|max:5000'
    ];
    protected $append = ['views', 'link', 'price_local', 'price_with_user_currency', 'final_price_with_user_currency', 'discount_with_user_currency'];

    public function toSearchableArray() {
        $array = [
            'id' => $this->id,
            'title' => $this->title,
        ];
        return $array;
    }

    public function getPriceLocalAttribute() {
        return changeRate($this->price, userCurrency()->id, $this->currency_id);
    }

    public function getFinalPriceLocalAttribute() {
        return changeRate($this->final_price, userCurrency()->id, $this->currency_id);
    }

    public static function boot() {
        parent::boot();
        static::created(function ($row) {
            if (!request()->hasFile('image') && !$row->image) {
                $image = generateImage($row->title, static::$attachFields['image']['sizes']);
                $data['image'] = $image;
                \DB::table('products')->where('id', $row->id)->update($data);
            }
        });
    }

    public function reviews() {
        return $this->hasMany(Review::class, 'product_id');
    }

    public function Category() {
        return $this->belongsTo(Category::class, 'category_id')->withTrashed()->withDefault();
    }

    public function currency() {
        return $this->belongsTo(Currency::class, 'currency_id')->withTrashed()->withDefault();
    }

    public function scopeActive($query) {
        return $query->where('is_active', '=', 1);
    }

    public function includes() {
        return $this->with(['category', 'currency']);
    }

    public function scopeFilterAndSort() {
        return $this->includes()
            ->when(request('category_id'), function ($q) {
                return $q->where('category_id', request('category_id'));
            })
            ->when(request('currency_id'), function ($q) {
                return $q->where('currency_id', request('currency_id'));
            })
            ->when(request('order_field'), function ($q) {
                return $q->orderBy((request('order_field')), (request('order_type')) ?: 'desc');
            })
            ->orderBy('id', 'desc');
    }

    public function export($rows, $fileName) {
        return (new \Rap2hpoutre\FastExcel\FastExcel($rows))
            ->download($fileName . "_" . date("Y-m-d H:i:s") . '.xlsx', function ($row) {
                return [
                    'ID' => $row->id,
                    'Category' => $row->category->title,
                    'Title' => $row->title,
                    'Summary' => $row->summary,
                    'Content' => $row->content,
                    'Price' => $row->price,
                    'Tags' => $row->tags,
                    'Image' => $row->image,
                    'Is Active' => ($row->is_active) ? trans('app.Yes') : trans('app.No'),
                    'Created at' => @$row->created_at,
                ];
            });
    }

    public function getLinkAttribute() {
        return lang() . '/products/details/' . $this->id . '/' . $this->slug;
    }

    public function getTitleLimitedAttribute() {
        return str_limit($this->title, 35);
    }

    public function getContentLimitedAttribute() {
        return str_limit(strip_tags($this->content), 60);
    }

    public function getPriceWithUserCurrencyAttribute() {
        return changeRate($this->price, userCurrency()->id, $this->currency_id);
    }

    public function getFinalPriceWithUserCurrencyAttribute() {
        return changeRate($this->final_price, userCurrency()->id, $this->currency_id);
    }

    public function getDiscountWithUserCurrencyAttribute() {
        return changeRate($this->discount, userCurrency()->id, $this->currency_id);
    }

}

backend/app/Http/Controllers/Admin/ProductsController.php
<?php

namespace App\Http\Controllers\Admin;

class ProductsController extends \App\Http\Controllers\Controller {

    public function __construct(\App\Models\Product $model) {
        $this->module = 'products';
        $this->title = trans('admin.Products');
        $this->model = $model;
        $this->rules = $model->rules;
        $this->reviewsModule = 'reviews';
    }

    public function getIndex() {
        $data['module'] = $this->module;
        $data['page_title'] = trans('app.List') . " " . $this->title;
        $data['rows'] = $this->model->filterAndSort()->paginate(env('PAGE_LIMIT', 10));
        $data['row'] = $this->model;
        $data['reviewsModule'] =$this->reviewsModule;
        return view('admin.' . $this->module . '.index', $data);
    }

    public function getCreate() {
        authorize('create-' . $this->module);
        $data['module'] = $this->module;
        $data['page_title'] = trans('app.Create') . " " . $this->title;
        $data['breadcrumb'] = [$this->title => 'admin/' . $this->module];
        $data['row'] = $this->model;
        $data['row']->is_active = 1;
        return view('admin.' . $this->module . '.create', $data);
    }

    public function postCreate() {
        authorize('create-' . $this->module);
        $this->validate(request(), $this->rules);
        if ($row = $this->model->create(request()->all())) {
            flash()->success(trans('app.Created successfully'));
            return redirect(lang() . '/admin/' . $this->module);
        }
        flash()->error(trans('app.failed to save'));
    }

    public function getEdit($id) {
        authorize('edit-' . $this->module);
        $data['module'] = $this->module;
        $data['page_title'] = trans('app.Edit') . " " . $this->title;
        $data['breadcrumb'] = [$this->title => 'admin/' . $this->module];
        $data['row'] = $this->model->findOrFail($id);
        return view('admin.' . $this->module . '.edit', $data);
    }

    public function postEdit($id) {
        authorize('edit-' . $this->module);
        $row = $this->model->findOrFail($id);
        $this->validate(request(), $this->rules);
        if ($row->update(request()->all())) {
            flash(trans('app.Update successfully'))->success();
            return back();
        }
    }

    public function getView($id) {
        authorize('view-' . $this->module);
        $data['module'] = $this->module;
        $data['page_title'] = trans('app.View') . " " . $this->title;
        $data['breadcrumb'] = [$this->title => 'admin/' . $this->module];
        $data['row'] = $this->model->findOrFail($id);
        return view('admin.' . $this->module . '.view', $data);
    }

    public function getDelete($id) {
        authorize('delete-' . $this->module);
        $row = $this->model->findOrFail($id);
        $row->delete();
        flash()->success(trans('app.Deleted Successfully'));
        return back();
    }

    public function getExport() {
        authorize('view-' . $this->module);
        $rows = $this->model->filterAndSort()->get();
        if ($rows->isEmpty()) {
            flash()->error(trans('app.There is no results to export'));
            return back();
        }
        return $this->model->export($rows, $this->module);
    }

}

backend/app/Http/Controllers/Api/ProductsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Validator;

class ProductsController extends Controller {
    /*
     * 200: success
     * 201 created
     * 401: unauthorized
     * 404: page not found
     * 400: Bad Request
     * 422: Validation error
     * 403: Forbidden
     */

    public function __construct(\App\Models\Product $model) {
        $this->model = $model;
    }

    public function index() {
        $rows = $this->model->filterAndSort()->paginate(env('PAGE_LIMIT', 10));
        return \App\Http\Resources\ProductResource::collection($rows);
    }

    public function show($id) {
        return new \App\Http\Resources\ProductResource($this->model->includes()->findOrFail($id));
    }

}

backend/app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

class ProductsController extends Controller {

    public $model;
    public $module;

    public function __construct(\App\Models\Product $model) {
        $this->module = 'products';
        $this->model = $model;
        $this->title = trans('app.Products');
    }

    public function getIndex() {
        $data['page_title'] = $this->title;
        $data['meta_description'] = conf('application_name') . ' : ' . $this->title;
        $data['meta_keywords'] = conf('application_name') . ',' . $this->title;
        $data['rows'] = $this->model->filterAndSort()->active()->orderBy('created_at', 'DESC')->paginate(9);
        return view('front.' . $this->module . '.index', $data);
    }

    public function getDetails($id, $slug = NULL) {
        $data['row'] = $this->model->filterAndSort()->active()->findOrFail($id);
        $data['breadcrumb'] = [$this->title => $this->module];
        $data['otherRows'] = $this->model->filterAndSort()->where('id', '!=', $id)->active()->inRandomOrder()->limit(5)->get();
        $data['page_title'] = $data['row']->title;
        $data['meta_description'] = ($data['row']->meta_description) ?: $data['row']->content_limited;
        $data['meta_keywords'] = $data['row']->meta_keywords;
        $data['image'] = $data['row']->image;
        /////////////////// update views
        $data['row']->increment('views');
        return view('front.' . $this->module . '.details', $data);
    }

}

backend/resources/views/admin/products/create.blade.php
@extends('layouts.admin')
@section('title')
<h6 class="slim-pagetitle">
    {{ @$page_title }}
</h6>
@endsection
@section('content')
<div class="section-wrapper">
    <div class="form-layout form-layout-4">
        {!! Form::model($row,['method' => 'post','files' => true] ) !!} 
        {{ csrf_field() }}
        @include('admin.'.$module.'.form',$row)
        <!-- custom-file -->
        <div class="form-layout-footer mg-t-30">
            <button class="btn btn-primary bd-0">{{ trans('admin.Save') }}</button>
        </div>
        {!! Form::close() !!}
        <!-- form-layout-footer -->
    </div>
    <!-- form-layout -->
</div>
@endsection

backend/resources/views/admin/products/edit.blade.php
@extends('layouts.admin')
@section('title')
<h6 class="slim-pagetitle">
    {{ @$page_title }}
</h6>
@endsection
@section('content')
<div class="section-wrapper">
    <div class="form-layout form-layout-4">
        {!! Form::model($row,['method' => 'post','files' => true] ) !!} {{ csrf_field() }}
        @include('admin.'.$module.'.form',$row)
        <!-- custom-file -->
        <div class="form-layout-footer mg-t-30">
            <button class="btn btn-primary bd-0">{{ trans('admin.Save') }}</button>
        </div>
        {!! Form::close() !!}
        <!-- form-layout-footer -->
    </div>
    <!-- form-layout -->
</div>
@endsection

backend/resources/views/admin/products/form.blade.php
@include('form.select',['name'=>'section_id','options'=>$row->getSectionsWithParents(),'attributes'=>['class'=>'form-control','label'=>trans('admin.Section'),'placeholder'=>trans('admin.Select Section'),'required'=>1]])

@foreach(langs() as $lang)
@php
$attributes=['class'=>'form-control','label'=>trans('admin.Title').' '.$lang,'placeholder'=>trans('admin.Title')];
if($lang=='en')
$attributes['required']=1;
@endphp
@include('form.input',['name'=>'title['.$lang.']','value'=>$row->getTranslation('title',$lang),'type'=>'text','attributes'=>$attributes])
@endforeach


@foreach(langs() as $lang)
@php
$attributes=['class'=>'form-control','label'=>trans('admin.Summary').' '.$lang,'placeholder'=>trans('admin.Summary')];
if($lang=='en')
$attributes['required']=1;
@endphp
@include('form.input',['name'=>'summary['.$lang.']','value'=>$row->getTranslation('summary',$lang),'type'=>'textarea','attributes'=>$attributes])
@endforeach


@foreach(langs() as $lang)
@php
$attributes=['class'=>'form-control editor','label'=>trans('admin.Content').' '.$lang,'placeholder'=>trans('admin.Content')];
if($lang=='en')
$attributes['required']=1;
@endphp
@include('form.input',['name'=>'content['.$lang.']','value'=>$row->getTranslation('content',$lang),'type'=>'textarea','attributes'=>$attributes])
@endforeach

@foreach(langs() as $lang)
@include('form.input',['name'=>'tags['.$lang.']','value'=>$row->getTranslation('tags',$lang),'type'=>'text','attributes'=>['class'=>'form-control tags','label'=>trans('admin.Tags').' '.$lang,'placeholder'=>trans('admin.Tags')]])
@endforeach


@include('form.input',['name'=>'unit_price','type'=>'number','attributes'=>['class'=>'form-control','label'=>trans('admin.Unit Price'),'placeholder'=>trans('admin.Unit Price'),'step'=>'0.01','required'=>1,'min'=>0,'pattern'=>'^\d*(\.\d{0,3})?$']])

@include('form.input',['name'=>'discount','type'=>'number','attributes'=>['class'=>'form-control','label'=>trans('admin.Discount'),'placeholder'=>trans('admin.Discount'),'step'=>'0.01','required'=>1,'min'=>0,'pattern'=>'^\d*(\.\d{0,3})?$']])


@include('form.file',['name'=>'image','attributes'=>['class'=>'form-control custom-file-input','label'=>trans('admin.Image'),'placeholder'=>trans('admin.Image')]])

@include('form.boolean',['name'=>'is_active','attributes'=>['label'=>trans('admin.Is active')]])

<h3><u>{{trans('admin.Search engine optmization')}}(SEO)</u></h3>
@foreach(langs() as $lang)
@include('form.input',['name'=>'meta_description['.$lang.']','value'=>$row->getTranslation('meta_description',$lang),'type'=>'textarea','attributes'=>['class'=>'form-control','label'=>trans('admin.Meta description').' '.$lang,'placeholder'=>trans('admin.Meta description')]])
@endforeach

@foreach(langs() as $lang)
@include('form.input',['name'=>'meta_keywords['.$lang.']','value'=>$row->getTranslation('meta_keywords',$lang),'type'=>'text','attributes'=>['class'=>'form-control tags','label'=>trans('admin.Meta keywords').' '.$lang,'placeholder'=>trans('admin.Meta keywords')]])
@endforeach



@push('js')
<script>
    $(function () {
    $('form').submit(function () {
    var title_en = $('input[name="title[en]"]').val();
            @foreach(langs() as $lang)
            if ($('input[name="title[{{$lang}}]"]').val() == '')
            $('input[name="title[{{$lang}}]"]').val(title_en);
            @endforeach

            var content_en = $('textarea[name="content[en]"]').val();
            @foreach(langs() as $lang)
            if ($('textarea[name="content[{{$lang}}]"]').val() == '')
            $('textarea[name="content[{{$lang}}]"]').val(content_en);
            @endforeach

            var summary_en = $('textarea[name="summary[en]"]').val();
            @foreach(langs() as $lang)
            if ($('textarea[name="summary[{{$lang}}]"]').val() == '')
            $('textarea[name="summary[{{$lang}}]"]').val(content_en);
            @endforeach
            
            var tags_en = $('input[name="tags[en]"]').val();
            @foreach(langs() as $lang)
            if ($('input[name="tags[{{$lang}}]"]').val() == '')
            $('input[name="tags[{{$lang}}]"]').val(tags_en);
            @endforeach
            
            var meta_description_en = $('textarea[name="meta_description[en]"]').val();
            @foreach(langs() as $lang)
            if ($('textarea[name="meta_description[{{$lang}}]"]').val() == '')
            $('textarea[name="meta_description[{{$lang}}]"]').val(meta_description_en);
            @endforeach

            var meta_keywords_en = $('input[name="meta_keywords[en]"]').val();
            @foreach(langs() as $lang)
            if ($('input[name="meta_keywords[{{$lang}}]"]').val() == '')
            $('input[name="meta_keywords[{{$lang}}]"]').val(meta_keywords_en);
            @endforeach

    });
    });
</script>
@endpush

backend/resources/views/admin/products/index.blade.php
@extends('layouts.admin')
@section('title')
<h6 class="slim-pagetitle">
    {{ @$page_title }}
    @if(can('create-'.$module))
    <a href="{{lang()}}/admin/{{$module}}/create" class="btn btn-success">
        <i class="fa fa-plus"></i> {{trans('admin.Create')}}
    </a>
    @endif
    @if(can('view-'.$module))
    <a href="{{lang()}}/admin/{{$module}}/export?{{@$_SERVER['QUERY_STRING']}}" class="btn btn-primary">
        <i class="fa fa-arrow-down"></i> {{trans('admin.Export')}}
    </a>
    @endif
</h6>
@endsection
@section('content')
<div class="section-wrapper">
    @include('admin.'.$module.'.partials.filters')
    @if(can('view-'.$module))
    @if (!$rows->isEmpty())
    <div class="table-responsive">
        <table class="table display responsive nowrap">
            <thead>
                <tr>
                    <th class="wd-5p">{{trans('admin.ID')}} </th>
                    <th class="wd-15p">{{trans('admin.Section')}} </th>
                    <th class="wd-5p">{{trans('admin.Image')}} </th>
                    <th class="wd-20p">{{trans('admin.Title')}} </th>
                    <th class="wd-5p">{{trans('admin.Price')}} </th>
                    <th class="wd-5p">{{trans('admin.Views')}} </th>
                    <th class="wd-5p">{{trans('admin.Active')}} </th>
                    <th class="wd-10p">{{trans('admin.Created by')}} </th>
                    <th class="wd-15p">{{trans('admin.Created at')}}</th>
                    <th class="wd-20p">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($rows as $row)
                <tr>
                    <td class="center">{{$row->id}}</td>
                    <td class="center">{{$row->section->title}}</td>
                    <td class="center">{!! image($row->image,'small',['width'=>50]) !!}</td>
                    <td class="center">{{$row->title_limited}}</td>
                    <td class="center">{{$row->final_price}}</td>
                    <td class="center">{{$row->views}}</td>
                    <td class="center"><img src="img/{{($row->is_active)?'check.png':'close.png'}}"></td>
                    <td class="center">{{@$row->creator->name}}</td>
                    <td class="center">{{$row->created_at}}</td>
                    <td class="center">
                        @if(can('view-'.$module))

                        <a class="btn-xs" href="{{lang()}}/admin/{{$reviewsModule}}?product_id={{$row->id}}" title={{trans('admin.Reviews')}} target="_blank">
                            <i class="icon fa fa-comment"></i>
                        </a>
                        @endif

                        @if(can('edit-'.$module))
                        <a class="btn btn-success btn-xs" href="{{lang()}}/admin/{{$module}}/edit/{{$row->id}}" title="{{trans('admin.Edit')}}">
                            <i class="fa fa-edit"></i>
                        </a>
                        @endif

                        @if(can('view-'.$module))
                        <a class="btn btn-primary btn-xs" href="{{lang()}}/admin/{{$module}}/view/{{$row->id}}" title="{{trans('admin.View')}}">
                            <i class="fa fa-eye"></i>
                        </a>
                        @endif

                        @if(can('delete-'.$module))
                        <a class="btn btn-danger btn-xs" href="{{lang()}}/admin/{{$module}}/delete/{{$row->id}}" title="{{trans('admin.Delete')}}" data-confirm="{{trans('admin.Are you sure you want to delete this item')}}?">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                        @endif
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="paganition-center"> 
        {!! $rows->appends([])->render() !!}
    </div>
    @else
    {{trans("admin.There is no results")}}
    @endif
    @endif
</div>
@endsection

backend/resources/views/admin/products/view.blade.php
@extends('layouts.admin')
@section('title')
<h6 class="slim-pagetitle">
    {{ @$page_title }}
</h6>
@endsection
@section('content')
<div class="section-wrapper">
    @if(can('edit-'.$module) )
    <a href="{{lang()}}/admin/{{$module}}/edit/{{$row->id}}" class="btn btn-success">
        <i class="fa fa-edit"></i> {{trans('admin.Edit')}}
    </a><br>
    @endif
    <div class="table-responsive">
        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered pull-left">
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Section')}}</td>
                <td width="75%" class="align-left">{{@$row->section->title}}</td>
            </tr>
            @foreach(langs() as $lang)
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Title')}} {{$lang}}</td>
                <td width="75%" class="align-left">{{@$row->getTranslation('title',$lang)}}</td>
            </tr>
            @endforeach

            @foreach(langs() as $lang)
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Slug')}} {{$lang}}</td>
                <td width="75%" class="align-left">{{@$row->getTranslation('slug',$lang)}}</td>
            </tr>
            @endforeach

            @foreach(langs() as $lang)
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Summary')}} {{$lang}}</td>
                <td width="75%" class="align-left">{{@$row->getTranslation('summary',$lang)}}</td>
            </tr>
            @endforeach

            @foreach(langs() as $lang)
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Content')}} {{$lang}}</td>
                <td width="75%" class="align-left">{!! @$row->getTranslation('content',$lang) !!}</td>
            </tr>
            @endforeach

            @foreach(langs() as $lang)
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Tags')}} {{$lang}}</td>
                <td width="75%" class="align-left">{{@$row->getTranslation('tags',$lang)}}</td>
            </tr>
            @endforeach
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Unit Price')}}</td>
                <td width="75%" class="align-left">{{$row->unit_price}} {{trans('app.EGP')}}</td>
            </tr>
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Discount')}}</td>
                <td width="75%" class="align-left">{{$row->discount}} {{trans('app.EGP')}}</td>
            </tr>
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Image')}}</td>
                <td width="75%" class="align-left">{!! image($row->image,'small') !!}</td>
            </tr>
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Is active')}}</td>
                <td width="75%" class="align-left"><img src="img/{{($row->is_active)?'check.png':'close.png'}}"></td>
            </tr>
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Created by')}}</td>
                <td width="75%" class="align-left">{{@$row->creator->name}}</td>
            </tr>
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Link')}}</td>
                <td width="75%" class="align-left">
                    <a href="{{app()->make("url")->to('/').'/'.@$row->link}}" target="_blank">
                        {{app()->make("url")->to('/').'/'.@$row->link}}
                    </a>
                </td>
            </tr>
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Views')}}</td>
                <td width="75%" class="align-left">{{@$row->views}}</td>
            </tr>
             @foreach(langs() as $lang)
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Meta description')}} {{$lang}}</td>
                <td width="75%" class="align-left">{{@$row->getTranslation('meta_description',$lang)}}</td>
            </tr>
            @endforeach

            @foreach(langs() as $lang)
            <tr>
                <td width="25%" class="align-left">{{trans('admin.Meta keywords')}} {{$lang}}</td>
                <td width="75%" class="align-left">{{@$row->getTranslation('meta_keywords',$lang)}}</td>
            </tr>
            @endforeach

        </table>
    </div>
</div>
@endsection